# Generated by Django 4.1.4 on 2023-02-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_retrieval",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
