# Generated by Django 4.1.4 on 2023-02-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_profile_last_retrieval"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="has_plus",
            field=models.BooleanField(default=False),
        ),
    ]
