# Generated by Django 4.1.4 on 2023-02-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_profile_has_plus"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
