# Generated by Django 4.1.4 on 2023-03-15 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_profile_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="indexing_type",
            field=models.IntegerField(
                choices=[(1, "None"), (2, "Metadata"), (3, "Content")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="account.account",
            ),
        ),
    ]
