# Generated by Django 4.1.7 on 2023-03-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_account_bookmarks_count_account_favorites_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_indexed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
