# Generated by Django 4.2 on 2023-04-22 13:11

from django.db import migrations
import ndarraydjango.fields


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_profile_last_indexed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="posts_vectors",
            field=ndarraydjango.fields.NDArrayField(
                blank=True, editable=True, null=True
            ),
        ),
    ]
