# Generated by Django 4.2 on 2023-05-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_profile_posts_vectors"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="generate_recommendations",
            field=models.BooleanField(default=False),
        ),
    ]
