# Generated by Django 4.2.1 on 2023-05-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_profile_send_daily_digest"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_sample_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
