# Generated by Django 4.2.9 on 2024-01-22 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_profile_last_sample_email_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="daily_digest_am",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="daily_digest_hour",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(11),
                ],
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="daily_digest_timezone",
            field=models.CharField(default="UTC"),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_daily_digest_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
