# Generated by Django 4.2.9 on 2024-01-23 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_profile_daily_digest_am_profile_daily_digest_hour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="daily_digest_minute",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(60),
                ],
            ),
        ),
    ]
