# Generated by Django 4.2.9 on 2024-01-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_profile_daily_digest_minute"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_index_error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
