# Generated by Django 4.1.4 on 2023-03-12 01:02

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    operations = [
        TrigramExtension(),
    ]
