# Generated by Django 4.2.1 on 2023-05-16 02:32

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import ndarraydjango.fields


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostVectors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("post_id", models.CharField(unique=True)),
                ("vectors", ndarraydjango.fields.NDArrayField(editable=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
